name: Auto Update Token

on:
  schedule:
    - cron: '0 */1 * * *'  # প্রতি ৪ ঘণ্টায় একবার চালাবে
  workflow_dispatch:

jobs:
  update-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install "requests[socks]"

      - name: Run Login Script
        run: python run.py

      - name: Commit save.txt if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add save.txt try.txt
          git commit -m "Auto update save.txt and try.txt" || echo "No changes to commit"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write
